default: true
allow_different_nesting: true

MD007:
  indent: 2

MD013:
  line_length: 999

MD024:
  allow_different_nesting: true

MD025:
  front_matter_title: ""

MD033: false

MD040: false

MD045: false
