repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    files: .*

- repo: https://github.com/markdownlint/markdownlint
  rev: v0.12.0
  hooks:
  - id: markdownlint
    files: \.(md|mdown|markdown)$

- repo: local
  hooks:
    - id: bundle-install
      name: Bundle install
      pass_filenames: false
      language: system
      entry: bundle install
    - id: rake-test
      name: Rake Test
      language: system
      entry: bundle exec rake test
