remote_theme: just-the-docs/just-the-docs@v0.5.1

plugins:
  - jekyll-seo-tag

title: "FFXIV Elemental Raid Macros"
description: "Final Fantasy XIV Elemental DC Raid Macros"

color_scheme: dark

aux_links:
  "Elemental DC Raid Macros Discord":
    - "https://discord.gg/WEzhVHwAU6"

aux_links_new_tab: true

enable_copy_code_button: true

back_to_top: true
back_to_top_text: "Back to top"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
